# -*- coding: utf-8 -*-
"""Energy Consumption Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11jFmzc2p77eqA8L0Pg6yDQguQrS3jLve
"""

import sqlite3
import pandas as pd
import numpy as np

# ----------------------------
# 1. Generate energy data
# ----------------------------
np.random.seed(42)
num_rows = 1000

regions = ['North', 'South', 'East', 'West', 'Central']
facilities = ['Plant A', 'Plant B', 'Plant C']
machines = ['Boiler', 'Pump', 'Compressor', 'Conveyor']
dates = pd.date_range(start='2023-01-01', periods=num_rows, freq='D')

data = {
    'record_id': range(1, num_rows+1),
    'date': np.random.choice(dates, num_rows),
    'region': np.random.choice(regions, num_rows),
    'facility': np.random.choice(facilities, num_rows),
    'machine': np.random.choice(machines, num_rows),
    'energy_kwh': np.round(np.random.uniform(50, 500, size=num_rows), 2)  # fixed!
}

df = pd.DataFrame(data)

conn = sqlite3.connect("energy_database.db")
df.to_sql("energy_usage", conn, if_exists="replace", index=False)
print("✓ Energy usage database created")
df.head()

query1 = """
SELECT region,
       SUM(energy_kwh) AS total_energy,
       ROUND(AVG(energy_kwh), 2) AS avg_energy
FROM energy_usage
GROUP BY region
ORDER BY total_energy DESC;
"""
df_region = pd.read_sql_query(query1, conn)
df_region

query2 = """
SELECT facility,
       SUM(energy_kwh) AS total_energy,
       ROUND(AVG(energy_kwh), 2) AS avg_energy
FROM energy_usage
GROUP BY facility
ORDER BY total_energy DESC;
"""
df_facility = pd.read_sql_query(query2, conn)
df_facility

# Query 3: Top 5 machines consuming the most energy
query3 = """
SELECT machine,
       SUM(energy_kwh) AS total_energy
FROM energy_usage
GROUP BY machine
ORDER BY total_energy DESC
LIMIT 5;
"""
df_machine = pd.read_sql_query(query3, conn)
df_machine

# Query 4: Monthly energy consumption trend
query4 = """
SELECT strftime('%Y-%m', date) AS month,
       SUM(energy_kwh) AS total_energy
FROM energy_usage
GROUP BY month
ORDER BY month;
"""
df_monthly = pd.read_sql_query(query4, conn)
df_monthly

# Query 5: High energy usage records (above average)
query5 = """
SELECT record_id, region, facility, machine, energy_kwh, date
FROM energy_usage
WHERE energy_kwh > (SELECT AVG(energy_kwh) FROM energy_usage)
ORDER BY energy_kwh DESC
LIMIT 10;
"""
df_high_usage = pd.read_sql_query(query5, conn)
df_high_usage